name: ASan / UBSan

on:
  schedule: [cron: '0 3 * * *']
  workflow_dispatch:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

concurrency:
  group: asan-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  asan:
    name: ASan + UBSan
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            clang \
            cmake \
            libavcodec-dev \
            libavdevice-dev \
            libavformat-dev \
            libavutil-dev \
            libexif-dev \
            libgl-dev \
            libopenal-dev \
            libopus-dev \
            libqrencode-dev \
            libsodium-dev \
            libsqlcipher-dev \
            libswscale-dev \
            libunwind-dev \
            libv4l-dev \
            libvpx-dev \
            libxss-dev \
            ninja-build \
            pkg-config \
            qt6-base-dev \
            qt6-l10n-tools \
            libqt6svg6-dev \
            qt6-tools-dev \
            qt6-tools-dev-tools \
            xvfb

      - name: Build toxcore
        run: |
          git clone --depth=1 --recursive https://github.com/TokTok/c-toxcore.git toxcore
          cmake -B toxcore/_build -S toxcore -GNinja -DBOOTSTRAP_DAEMON=OFF
          cmake --build toxcore/_build
          sudo cmake --install toxcore/_build
          sudo ldconfig

      - name: Configure
        run: cmake --preset asan -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build --preset asan --parallel $(nproc)

      - name: Run tests
        run: |
          ASAN_OPTIONS=detect_leaks=0:abort_on_error=0 \
          xvfb-run --auto-servernum \
            ctest --test-dir _build-asan --parallel $(nproc) --output-on-failure
